# Building an Artificial Neural Network: Churn Modelling

# 1. Data Preprocessing

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

/home/raul/anaconda3/envs/deep_learning/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Load the raw data

In [2]:
data_set = pd.read_csv("Churn_Modelling.csv")
X = data_set.iloc[:,3:13].values
y = data_set.iloc[:,13].values

In [3]:
data_set.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

Transform the categorical data to numerical

In [4]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [5]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [6]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [7]:
X[7]

array([  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
         3.76000000e+02,   0.00000000e+00,   2.90000000e+01,
         4.00000000e+00,   1.15046740e+05,   4.00000000e+00,
         1.00000000e+00,   0.00000000e+00,   1.19346880e+05])

In [8]:
X = X[:,1:]

Split data in train and test dataset

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, 
                                                    random_state = 42)

Apply of feature scaling

In [10]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
X_train.shape

(8000, 11)

# 2. Building the ANN

In [12]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


Initialize the ANN

In [13]:
classifier = Sequential()

Configuration of the ANN:

* Hidden layer 1: inputs --> 11, units(output) --> 6, activation --> Relu
* Hidden layer 2: units(output) --> 6, activation --> Relu
* Output layer: units(output) --> 1, activation -->

**Tip1**: number of units in the hidden(s) layer: average between input and output layers

**Tip2**: activation function for the output layer:
    * binary: "sigmoid"
    * multiclass: "softmax"


In [14]:
classifier.add(Dense(units = 6, kernel_initializer="uniform", 
                     activation = "relu", input_dim = 11))
classifier.add(Dense(units = 6, kernel_initializer="uniform", 
                     activation = "relu"))
classifier.add(Dense(units = 1, kernel_initializer="uniform", 
                     activation = "sigmoid"))

Compile the ANN

* Optimizer: stocastic gradient descent "adam"
* Loss: "binary_crossentropy"
* Metrics: "accuracy"


**Tip1**: loss function: 
* "binary_crossentropy" for binary categorical outputs
* "categorical_crossentropy" for multiclass categorical outputs

In [15]:
classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy'])

Fit the neural network

In [16]:
classifier.fit(x=X_train, y=y_train, batch_size=10, epochs=20)

Epoch 1/20
8000/8000 [==============================] - 1s - loss: 0.4884 - acc: 0.7940     
Epoch 2/20
8000/8000 [==============================] - 0s - loss: 0.4309 - acc: 0.7945     
Epoch 3/20
8000/8000 [==============================] - 0s - loss: 0.4248 - acc: 0.8037     
Epoch 4/20
8000/8000 [==============================] - 1s - loss: 0.4207 - acc: 0.8226     
Epoch 5/20
8000/8000 [==============================] - 1s - loss: 0.4182 - acc: 0.8275     
Epoch 6/20
8000/8000 [==============================] - 1s - loss: 0.4169 - acc: 0.8305     
Epoch 7/20
8000/8000 [==============================] - 1s - loss: 0.4146 - acc: 0.8304     
Epoch 8/20
8000/8000 [==============================] - 1s - loss: 0.4139 - acc: 0.8319     
Epoch 9/20
8000/8000 [==============================] - 1s - loss: 0.4125 - acc: 0.8341     
Epoch 10/20
8000/8000 [==============================] - 1s - loss: 0.4124 - acc: 0.8319     
Epoch 11/20
8000/8000 [==============================] - 1s - loss: 0

## 3. Evaluation of the model (I)

In [17]:
y_pred = classifier.predict(X_test)
y_pred = y_pred > 0.5

In [18]:
y_pred[:10]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]], dtype=bool)

In [19]:
cm = confusion_matrix(y_test, y_pred)

In [20]:
cm

array([[1558,   49],
       [ 275,  118]])

In [21]:
accuracy_test = accuracy_score(y_test, y_pred)

In [22]:
accuracy_test

0.83799999999999997

## 4. Single prediction

In [23]:
features = np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])

In [24]:
features.shape

(1, 11)

We have to rescale the features

In [25]:
features = sc.transform(features)

In [26]:
new_prediction = classifier.predict(features)[0]

In [27]:
new_prediction > 0.5

array([False], dtype=bool)

## 5. Evaluation, Improving and Tuning the ANN

In [28]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [45]:
def build_classifier():
    
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer="uniform", 
                     activation = "relu", input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer="uniform", 
                     activation = "relu"))
    classifier.add(Dense(units = 1, kernel_initializer="uniform", 
                     activation = "sigmoid"))
    classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy'])
    
    return classifier
    

In [46]:
classifier_cv = KerasClassifier(build_fn=build_classifier, batch_size = 10, epochs = 10)

In [47]:
accuracies = cross_val_score(estimator = classifier_cv, X = X_train, 
                             y = y_train, cv = 10, n_jobs = 1, verbose=True)

Epoch 1/10
7200/7200 [==============================] - 0s - loss: 0.5175 - acc: 0.7928     
Epoch 2/10
7200/7200 [==============================] - 0s - loss: 0.4243 - acc: 0.8065     
Epoch 3/10
7200/7200 [==============================] - 0s - loss: 0.4099 - acc: 0.8232     
Epoch 4/10
7200/7200 [==============================] - 0s - loss: 0.3995 - acc: 0.8244     
Epoch 5/10
7200/7200 [==============================] - 0s - loss: 0.3926 - acc: 0.8272     
Epoch 6/10
7200/7200 [==============================] - 0s - loss: 0.3868 - acc: 0.8297     
Epoch 7/10
7200/7200 [==============================] - 0s - loss: 0.3826 - acc: 0.8294     
Epoch 8/10
7200/7200 [==============================] - 0s - loss: 0.3792 - acc: 0.8308     
Epoch 9/10
7200/7200 [==============================] - 0s - loss: 0.3759 - acc: 0.8401     
Epoch 10/10
7200/7200 [==============================] - 1s - loss: 0.4885 - acc: 0.7940     
Epoch 2/10
7200/7200 [==============================] - 1s - loss: 0.

[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:  1.6min finished


In [48]:
accuracies

array([ 0.87249999,  0.84      ,  0.80749999,  0.8125    ,  0.84249999,
        0.84624999,  0.84499999,  0.81      ,  0.85749999,  0.85874999])

In [49]:
mean_accu = accuracies.mean()
variance_accu = accuracies.std()
print("Accuracy --> Mean: {0}; Standard Variation: {1}".format(mean_accu, variance_accu))

Accuracy --> Mean: 0.8392499948665499; Standard Variation: 0.02119256875185233


## 6. Improving the ANN

### 6.1 Dropout

Reduce overfitting, reduce the high variance 

In [50]:
from keras.layers import Dropout

In [51]:
classifier_drop = Sequential()

classifier_drop.add(Dense(units = 6, kernel_initializer="uniform", 
                 activation = "relu", input_dim = 11))
classifier_drop.add(Dropout(0.1))

classifier_drop.add(Dense(units = 6, kernel_initializer="uniform", 
                 activation = "relu"))
classifier_drop.add(Dropout(0.1))

classifier_drop.add(Dense(units = 1, kernel_initializer="uniform", 
                 activation = "sigmoid"))

classifier_drop.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy'])

### 6.2 Tuning the ANN

Parameter tunning --> grid search

We are going to tune:

* batch_size
* epochs

In [52]:
from sklearn.model_selection import GridSearchCV

In [53]:
def build_classifier(optimizer):
    
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer="uniform", 
                     activation = "relu", input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer="uniform", 
                     activation = "relu"))
    classifier.add(Dense(units = 1, kernel_initializer="uniform", 
                     activation = "sigmoid"))
    classifier.compile(optimizer=optimizer, loss="binary_crossentropy", metrics=['accuracy'])
    
    return classifier

In [54]:
classifier_gs = KerasClassifier(build_fn=build_classifier)

In [55]:
# parameters = {'batch_size': [25, 32],
#               'epochs':[10, 20],
#               'optimizer': ['adam', 'rmsprop']}

parameters = {'batch_size': [25, 32],
              'epochs':[10],
              'optimizer': ['adam']}

In [56]:
grid_search = GridSearchCV(estimator=classifier_gs, 
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)

In [57]:
grid_search_fit = grid_search.fit(X_train, y_train)

Epoch 1/10
7200/7200 [==============================] - 0s - loss: 0.5579 - acc: 0.7919     
Epoch 2/10
7200/7200 [==============================] - 0s - loss: 0.4404 - acc: 0.7933     
Epoch 3/10
7200/7200 [==============================] - 0s - loss: 0.4349 - acc: 0.7933     
Epoch 4/10
7200/7200 [==============================] - 0s - loss: 0.4311 - acc: 0.7933     
Epoch 5/10
7200/7200 [==============================] - 0s - loss: 0.4274 - acc: 0.7933     
Epoch 6/10
7200/7200 [==============================] - 0s - loss: 0.4242 - acc: 0.7971     
Epoch 7/10
7200/7200 [==============================] - 0s - loss: 0.4203 - acc: 0.8226     
Epoch 8/10
7200/7200 [==============================] - 0s - loss: 0.4158 - acc: 0.8321     
Epoch 9/10
7200/7200 [==============================] - 0s - loss: 0.4121 - acc: 0.8317     
Epoch 10/10
7200/7200 [==============================] - 0s - loss: 0.5418 - acc: 0.7947     
Epoch 2/10
7200/7200 [==============================] - 0s - loss: 0.

In [58]:
best_parameters = grid_search_fit.best_params_
best_accuracy = grid_search_fit.best_score_

In [59]:
print("Best Parameters: {0}".format(best_parameters))
print("Best Accuracies: {0}".format(best_accuracy))

Best Parameters: {'optimizer': 'adam', 'epochs': 10, 'batch_size': 25}
Best Accuracies: 0.830375
