# Building an Artificial Neural Network: Churn Modelling

# 1. Data Preprocessing

In [43]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

Load the raw data

In [49]:
data_set = pd.read_csv("Churn_Modelling.csv")
X = data_set.iloc[:,3:13].values
y = data_set.iloc[:,13].values

In [55]:
data_set.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

Transform the categorical data to numerical

In [51]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [52]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [53]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [58]:
X[7]

array([  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
         3.76000000e+02,   0.00000000e+00,   2.90000000e+01,
         4.00000000e+00,   1.15046740e+05,   4.00000000e+00,
         1.00000000e+00,   0.00000000e+00,   1.19346880e+05])

In [12]:
X = X[:,1:]

Split data in train and test dataset

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, 
                                                    random_state = 42)

Apply of feature scaling

In [15]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
X_train.shape

(8000, 11)

# 2. Building the ANN

In [18]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Initialize the ANN

In [32]:
classifier = Sequential()

Configuration of the ANN:

* Hidden layer 1: inputs --> 11, units(output) --> 6, activation --> Relu
* Hidden layer 2: units(output) --> 6, activation --> Relu
* Output layer: units(output) --> 1, activation -->

**Tip1**: number of units in the hidden(s) layer: average between input and output layers

**Tip2**: activation function for the output layer:
    * binary: "sigmoid"
    * multiclass: "softmax"


In [33]:
classifier.add(Dense(units = 6, kernel_initializer="uniform", 
                     activation = "relu", input_dim = 11))
classifier.add(Dense(units = 6, kernel_initializer="uniform", 
                     activation = "relu"))
classifier.add(Dense(units = 1, kernel_initializer="uniform", 
                     activation = "sigmoid"))

Compile the ANN

* Optimizer: stocastic gradient descent "adam"
* Loss: "binary_crossentropy"
* Metrics: "accuracy"


**Tip1**: loss function: 
* "binary_crossentropy" for binary categorical outputs
* "categorical_crossentropy" for multiclass categorical outputs

In [34]:
classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy'])

Fit the neural network

In [35]:
classifier.fit(x=X_train, y=y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 2s 218us/step - loss: 0.4801 - acc: 0.7945
Epoch 2/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.4301 - acc: 0.7945
Epoch 3/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.4242 - acc: 0.8011
Epoch 4/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.4209 - acc: 0.8250
Epoch 5/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.4182 - acc: 0.8291
Epoch 6/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.4162 - acc: 0.8305
Epoch 7/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.4141 - acc: 0.8321
Epoch 8/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.4127 - acc: 0.8324
Epoch 9/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.4117 - acc: 0.8332
Epoch 10/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4110 - acc: 0.8314

8000/8000 [==============================] - 1s 160us/step - loss: 0.3989 - acc: 0.8372
Epoch 83/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.3988 - acc: 0.8371
Epoch 84/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3989 - acc: 0.8360
Epoch 85/100
8000/8000 [==============================] - 2s 194us/step - loss: 0.3987 - acc: 0.8369
Epoch 86/100
8000/8000 [==============================] - 1s 164us/step - loss: 0.3981 - acc: 0.8350
Epoch 87/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.3979 - acc: 0.8381
Epoch 88/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.3969 - acc: 0.8370
Epoch 89/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.3975 - acc: 0.8362
Epoch 90/100
8000/8000 [==============================] - 2s 208us/step - loss: 0.3968 - acc: 0.8384
Epoch 91/100
8000/8000 [==============================] - 2s 218us/step - loss: 0.3969 - acc: 0.8384
Epo

## 3. Evaluation of the model (I)

In [76]:
y_pred = classifier.predict(X_test)
y_pred = y_pred > 0.5

In [77]:
y_pred[:10]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]], dtype=bool)

In [78]:
cm = confusion_matrix(y_test, y_pred)

In [79]:
cm

array([[1551,   56],
       [ 264,  129]])

In [80]:
accuracy_test = accuracy_score(y_test, y_pred)

In [81]:
accuracy_test

0.83999999999999997

## 4. Single prediction

In [96]:
features = np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])

In [97]:
features.shape

(1, 11)

We have to rescale the features

In [98]:
features = sc.transform(features)

In [99]:
new_prediction = classifier.predict(features)[0]

In [100]:
new_prediction > 0.5

array([False], dtype=bool)